### ISSUE TITLE
--features 'S' bug

### ISSUE THREAD

**Issue by Haoxi2002** [cui-jia-hua/TPRNN#1]
Hello, I am very interested in your work.
But I found two issues:
1. Some of dependency in your requirements.txt is missing. If you want to successfully run your project, you will need to install additional dependency.
2. I can't run when I set features 'S', The error message is as follows: 
> Traceback (most recent call last):
  File "D:\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "exp_start.py", line 138, in <module>
    exp.train(setting)
  File "H:\TPRNN\exp\exp_main.py", line 170, in train
    outputs = self._forward_propagation(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "H:\TPRNN\exp\exp_main.py", line 80, in _forward_propagation
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "E:\anaconda3\envs\TPRNN\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\TPRNN\models\TPRNN.py", line 242, in forward
    scaled_x = self.scale_construct(x, self.CSICB)[::-1]
  File "E:\anaconda3\envs\TPRNN\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\TPRNN\models\TPRNN.py", line 73, in forward
    all_inputs.append(temp_input.transpose(1, 2))
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

**Comment by Haoxi2002** [comment]
It looks like it's because you use .squeeze().
I suggest the following modifications:
```python
# in TPRNN.Scale_Construct
if len(temp_input.shape) == 2:
    temp_input = temp_input.unsqueeze(1)

# in TPRNN.model
if len(y.shape) == 2:
    y = y.unsqueeze(2)
```
